"""initial

Revision ID: 45c58ffb5042
Revises: fcdc798b6d1c
Create Date: 2025-05-21 19:43:40.526880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45c58ffb5042'
down_revision: Union[str, None] = 'fcdc798b6d1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'filename_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('filename_id', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
