"""initial

Revision ID: 742359cc6029
Revises: 425713723987
Create Date: 2025-06-07 21:20:40.704313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '742359cc6029'
down_revision: Union[str, None] = '425713723987'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('filename_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'documents', 'files', ['filename_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'filename_id')
    # ### end Alembic commands ###
