FROM python:3.10-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    gcc \
    && rm -rf /var/lib/apt/lists/*

COPY . .
RUN pip install --upgrade pip

RUN pip install -r requirements.txt


CMD ["/app/start.sh"]
